[package]
name = "xbulk-meta"
version = "2.0.0"
edition = "2021"
publish = false
authors = ["Alessandro De Franceschi <info@defralcoding.it>"]

[dev-dependencies]
[dependencies.xbulk]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.1"
